### ISSUE TITLE
无法打开应用

### ISSUE THREAD

**Issue by rty813** [ingbyr/GUI-YouGet#35] opened 2018-01-23 09:52 UTC
我通过java -jar .\GUI-YouGet.jar，运行，提示错误如下：
1月 23, 2018 5:46:56 下午 tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
信息: Installing CSS url handler, since it was not picked up automatically
Exception in Application start method
1月 23, 2018 5:46:57 下午 tornadofx.DefaultErrorHandler uncaughtException
严重: Uncaught error
java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter
        at com.jfoenix.controls.JFXTextField$StyleableProperties.<clinit>(JFXTextField.java:266)
        at com.jfoenix.controls.JFXTextField.<init>(JFXTextField.java:171)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
        at tornadofx.UIComponent.loadFXML(Component.kt:848)
        at tornadofx.UIComponent$fxml$1.<init>(Component.kt:828)
        at tornadofx.UIComponent.fxml(Component.kt:827)
        at tornadofx.UIComponent.fxml$default(Component.kt:827)
        at com.ingbyr.guiyouget.views.MainView.<init>(MainView.kt:30)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/java.lang.Class.newInstance(Unknown Source)
        at tornadofx.FXKt.find(FX.kt:408)
        at tornadofx.FXKt.find$default(FX.kt:393)
        at tornadofx.App.start(App.kt:86)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.PaintConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 35 more

我是Java9，有影响吗？

**Comment by ingbyr** [comment] 2018-01-23 09:57
目前不支持JRE9，可以先使用exe安装或者安装JRE8

**Comment by rty813** [comment] 2018-01-23 09:58
好吧，，谢谢

**Comment by ingbyr** [comment] 2018-01-23 10:01
duplicate of #33

**Comment by ingbyr** [comment] 2018-01-23 10:03
Duplicate of #33

**Closed** 2018-01-23 10:03 UTC
